name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '18'
