name: Install sqlserver-cmdlineutils

on: [push, pull_request]

jobs:
  install-sqlserver-cmdlineutils:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Chocolatey
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install sqlserver-cmdlineutils
      shell: pwsh
      run: |
        choco install sqlserver-cmdlineutils
        "C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn" | Out-File -FilePath $env:GITHUB_PATH -Append

    - name: Create server instance
      shell: pwsh
      run: |
        SqlLocalDB.exe create "TestLocalDBInstance"
        SqlLocalDB.exe start "TestLocalDBInstance"

    - name: Create test DB
      shell: pwsh
      run: |
        sqlcmd -S "(localdb)\TestLocalDBInstance" -Q "CREATE DATABASE testDatabase"
