name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Update Ubuntu
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ghc-8.10.7 cabal-install-3.4  # Installing specific versions of ghc and cabal-install
          cabal update
          cabal install darcs
          cabal install darcs
