name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Update Ubuntu
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ghc cabal-install
          cabal update
          cabal install cabal-install-3.10.1.0  # Pinning a compatible version of Cabal
          cabal install darcs
