name: Build
on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}

    steps:
      - name: Update Ubuntu
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sSL https://get-ghcup.haskell.org | sh -s -- -y
          source $HOME/.ghcup/env
          ghcup install ghc 8.10.7
          ghcup set ghc 8.10.7
          ghcup install cabal 3.4.0.0
          ghcup set cabal 3.4.0.0
         
