name: Build, Test and Validate Darcs

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t darcs-ubuntu-24.04 .

      - name: Run Docker container and validate darcs
        run: |
          docker run --rm darcs-ubuntu-24.04 
          darcs --version
          
