name: Install and Check MDATP

on: [push,pull_request]

jobs:
  install-and-check-mdatp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update package list
      run: sudo apt-get update

    - name: Install prerequisites
      run: sudo apt-get install -y curl libplist-utils

    - name: Download Microsoft Defender package
      run: |
        curl -O https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update

    - name: Install Microsoft Defender ATP
      run: sudo apt-get install -y mdatp

    - name: Verify MDATP License
      run: |
        if ! mdatp health | grep -q "License status: Licensed"; then
          echo "No valid license found. Please ensure MDATP is properly licensed."
          exit 1
        fi

    - name: Enable real-time protection
      run: sudo mdatp config real-time-protection --value enabled

    - name: Trigger activity for real-time protection
      run: sudo mdatp scan full

    - name: Check MDATP health
      run: mdatp health

    - name: Run MDATP Diagnostic
      run: mdatp diagnostic real-time-protection-statistics --output json
