name: Docker container 
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Start MSSQL Container
        run: |
          docker run -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=YourStrong!Passw0rd' --name mssql --memory=4g --cpus=2 --detach mcr.microsoft.com/mssql/server:2019-CU18-ubuntu-20.04
          sleep 120
          docker ps
          docker logs mssql
