name: Install Node.js

on: [push, pull_request]

jobs:
  install-nodejs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node.js
      run: |
        pwsh -command "Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/tj/n/master/bin/n' -OutFile '$HOME/n'"
        pwsh -command "& '$HOME/n' $env:default_version"

    - name: Check Node.js version
      run: node -v
