name: Install Node.js

on: [push, pull_request]

jobs:
  install-node:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js 18
      run: |
        $defaultVersion = 18
        $versionToInstall = Resolve-ChocoPackageVersion -PackageName "nodejs" -TargetVersion $defaultVersion
        Install-ChocoPackage "nodejs" -ArgumentList "--version=$versionToInstall"
      shell: pwsh
