name: Install Node.js

on: [push, pull_request]

jobs:
  install-node:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Setup Node.js 18 using n (if necessary)
      shell: pwsh
      run: |
        $defaultVersion = "18"
        Invoke-WebRequest -Uri "https://raw.githubusercontent.com/tj/n/master/bin/n" -OutFile "$HOME\n"
        & "$HOME\n" $defaultVersion
