name: Install Python on Windows 2022

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        

    - name: Verify Python installation
      run: python --version
