name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies and tutorial requirements
      run: |
        install.packages("remotes")
        remotes::install_cran(
          c("dplyr", "IRkernel", "reticulate"),
          dependencies = TRUE,
        )
        IRkernel::installspec()
      shell: Rscript {0}
