name: Install Miniforge

on: [push,pull_request]
jobs:
  install_dependencies:
    runs-on: ubuntu-22.04

    steps:
    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install R dependencies
      run: |
        R -e "install.packages(c('remotes', 'Rcpp'))"
        R -e "remotes::install_cran(c('IRkernel', 'reticulate'), dependencies = TRUE)"

    - name: Install Jupyter via pip
      run: |
        pip install jupyter

    - name: Configure IRkernel
      run: |
        Rscript -e "IRkernel::installspec()"
        
        # Uncomment below lines for debugging if needed
        # Rscript -e "print(reticulate::py_config())"
        # Rscript -e "reticulate::py_run_string('import os; print(os.environ)')"
