name: Get File Thumbprint

on: [push,pull_request]

jobs:
  thumbprint:
    runs-on: windows-2019

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Visual Studio Installer
      run: Invoke-WebRequest -Uri https://msedgedriver.azureedge.net/$latestVersion/edgedriver_win64.zip
      shell: pwsh

    - name: Get Signature Thumbprint
      id: get_thumbprint
      run: |
        $filePath = "vs_Enterprise.exe"
        $sig = Get-AuthenticodeSignature -FilePath $filePath
        $thumbprint = $sig.SignerCertificate.Thumbprint
        Write-Output "Signature Thumbprint: $thumbprint"
        echo "thumbprint=$thumbprint" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Output Thumbprint
      run: |
        echo "Signature Thumbprint: $env:thumbprint"
