name: CI

on: [push, pull_request]

jobs:
  docker-setup:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Info
        run: docker info
