name: CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        docker_channel:
          - stable

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Set BuildKit
        run: echo "export DOCKER_BUILDKIT=1" >> $GITHUB_ENV

      - name: Enable Experimental Docker Features
        run: |
          if [ ! -f /var/run/docker.pid ]; then
            echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
            sudo systemctl restart docker
          else
            echo "Docker is already running. Skipping restart."
          fi

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
        with:
          docker_channel: ${{ matrix.docker_channel }}

      - name: Install requirements
        run: |
          pip install DockerBuildManagement
      
      - name: Publish
        run: |
          dbm -build -publish prod
