name: CD

on:
  push:
    branches: ["setup-docker"]
  pull_request:
    branches: ["setup-docker"]
  workflow_dispatch:
 
    

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        docker_channel:
          - stable

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: setup Docker
        uses: docker-practice/actions-setup-docker@v1.0.0
        with:
          docker_channel: ${{ matrix.docker_channel }}

