name: CD

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        docker_channel:
          - stable

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: setup Docker
        uses: docker/setup-buildx-action@v2
        with:
          docker_channel: ${{ matrix.docker_channel }}

      - name: Start and enable Docker service
        run: |
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Install requirements
        run: |
          pip install DockerBuildManagement
      
      - name: Publish
        run: |
          dbm -build -publish prod
