name: Run gsutil on Ubuntu 24 ARM64

on: [push, pull_request]

jobs:
  install-gsutil:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12' 

    - name: Install gsutil
      run: |
        python -m pip install --upgrade pip
        pip install gsutil

    - name: Verify gsutil installation
      run: gsutil version
